### ISSUE TITLE
Error when tagging with 'German'

### ISSUE THREAD

**Issue by tteguayco** [JMendes1995/py_heideltime#13]
I get the following error when tagging a text setting "Germany" as language:

```
>>> results = py_heideltime('Lieferung 16.07.2020 - 17.07.2020', language='Germany')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\tegua\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\tegua\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\tegua\AppData\Local\Programs\Python\Python37\lib\site-packages\py_heideltime\py_heideltime.py", line 152, in exec_java_heideltime
    myCmd = subprocess.run(java_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 33: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tegua\AppData\Local\Programs\Python\Python37\lib\site-packages\py_heideltime\py_heideltime.py", line 85, in py_heideltime
    repeat(document_type), repeat(document_creation_time),repeat(date_granularity)))
  File "C:\Users\tegua\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\tegua\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 33: invalid start byte
```

![image](https://user-images.githubusercontent.com/20015750/87231681-080e3d00-c3b1-11ea-8094-6c30e40aa5df.png)

By the way, the name of the language should be "German", not "Germany" (which is the name of the country) :-)

Anyhow, this library looks amazing! Great job here.

**Comment by JMendes1995** [comment]
Hi @tteguayco 
Ty for your message and feedback.
About the issue. You are right, the name of language are German instead of Germany that is causing the bug. 

I recommend that you download the package again and run py_heideltime this way. 

`from py_heideltime import py_heideltime
results = py_heideltime('Lieferung 16.07.2020 - 17.07.2020', language='German')`

I am sorry for my mistake in describing the German Language. 
Please let me know if you still have the error.

Best regards

**Comment by tteguayco** [comment]
Hi @JMendes1995 
It's working smoothly now with German!

As said before, thanks a lot for this amazing wrapper, pretty useful for an interesting library I'm currently developing.

Regards!

**Comment by JMendes1995** [comment]
Great and good luck with your library. 
i am exited to try out you new library :).

Best regards.

closing this issue.
